"""Regenerate the natural-English demo corpus (data/natural/).

Internal tool for producing the shipped persona corpus. The corpus itself
is described in user-facing docs simply as natural-English prose by five
author personas — this script is how it was produced.

Design goals (see README "The demo corpora"):

  * Natural English with a large open vocabulary and realistic word
    statistics. LERF (Ch.6) is defined over natural language, and its
    advantage over count-based estimators appears exactly when the
    sample misses rare types of a rich vocabulary whose overall shape
    follows ordinary English. Prose is therefore generated by a local
    GPT-2 continuing a large pool of everyday-topic seed paragraphs.
  * Authorship signal carried by STYLE, not topic — mirroring the
    thesis's real benchmarks (e.g. CCAT50), where authors write about
    the same subjects and differ in function-word habits. All personas
    draw seeds from the same shared topic pool; each persona applies a
    distinct stylistic fingerprint (preferred adverbs and connectives,
    sentence-length rhythm, mild punctuation habits) in a post-
    processing pass over the generated prose.
  * Size: 50 train / 20 test documents per author, ~120-350 words each,
    so the thesis's headline Linear SVM can learn from LERF profiles.

Usage:
    python scripts/generate_natural_corpus.py            # write to data/natural/
    python scripts/generate_natural_corpus.py --n-train 50 --n-test 20
"""

from __future__ import annotations

import argparse
import os
import random
import re
import sys

import pandas as pd

TEXT_COL = "text"
TAG_COL = "author_tag"

SEED = 7

# ---------------------------------------------------------------------------
# Persona seed sentences — ONE persona-domain anchor sentence opens each
# document (the topical hook for attribution), while the body continues
# from generic prompts so the corpus-level word statistics stay near
# GPT-2's native distribution (see GENERIC_PROMPTS).
# ---------------------------------------------------------------------------

PERSONA_SEEDS = {
    "author00": [
        "Knights gathered in the great hall, and their banners hung from "
        "every rafter while torches guttered in the drafts.",
        "A squire crossed wet courtyard stones at first light, hauling "
        "his lord's armour from forge to chapel before the garrison woke.",
        "Siege provisions had arrived by cart, and stewards counted "
        "salted beef, firewood, and lamp oil against a long blockade.",
        "Heralds rehearsed tournament proclamations beneath cold "
        "battlements, each cadence practised until it carried.",
        "The keep's chronicle recorded that winter how Lady Ysolde "
        "shortened feasts, rationed tallow, and doubled watch rotations.",
        "Drawbridge chains rattled as riders returned from the northern "
        "marches, mud-caked and hoarse from three days of rain.",
        "In the armoury, a smith inspected every lance and visor, "
        "tapping hauberks and re-edging blades for the coming muster.",
        "Chaplains blessed the new banner before the garrison assembled, "
        "and oaths were renewed in a circle of steel.",
        "A herald's trumpet announced the first pairing of the tourney, "
        "and the crowd pressed against the lists to watch the unseating.",
        "The harvest carts rolled through before dusk, and farmers "
        "argued over tithe weights with the reeve at the gatehouse.",
        "The seneschal's ledger grew columns of debt as the castle "
        "hosted an ever-growing retinue of allies.",
        "The great hearth threw a ruddy light over scarred visors and "
        "sunburnt faces after the long day on the walls.",
        "A warhorse shied at a falling shield and unseated its rider in "
        "the warm-up lists, to general laughter and some cursing.",
        "The garrison's archers practised at straw butts in the outer "
        "yard, their arrows hissing through a thin cold drizzle.",
        "In the scriptorium, a monk copied out dispatches, his ink "
        "freezing in the unheated stone of the north tower.",
        "The garrison was doubled at the news of a fleet gathering "
        "across the water, and the beacon on the headland was lit.",
        "A travelling juggler entertained the household with feats of "
        "balance and fire, and was rewarded with bread and a bed.",
        "Masons inspected the outer curtain for cracks, marking stones "
        "for replacement before winter frosts could widen them.",
        "The falconer released his bird at sunrise, and the whole "
        "household paused to watch it climb above the towers.",
        "The drawbridge was raised at dusk as a precaution, and the "
        "watch argued quietly about whether the figure on the road was "
        "a messenger or a deserter.",
    ],
    "author01": [
        "The research vessel anchored over the deep basin at first "
        "light, and crew prepared sonar and trawl gear for the day's "
        "survey work.",
        "Salinity and temperature were logged at every station along "
        "the transect, from turbid coastal water out to the clear abyss.",
        "Divers descended along the buoy line to census the kelp "
        "forest, counting urchins where grazers had stripped the "
        "fronds to stubble.",
        "In the laboratory, sediment cores were sectioned and dated, "
        "and each layer of laminated mud matched a century of "
        "circulation change.",
        "Plankton samples drawn at dawn showed a bloom already under "
        "way, with diatoms dominating every slide under the scope.",
        "The whale survey logged eleven sightings before noon, and "
        "photo-identification matched two individuals to last "
        "season's catalogue.",
        "A hydrothermal vent field was mapped by towed camera, and "
        "the tube-worm colonies appeared unaffected by earlier "
        "sampling visits.",
        "Oceanographers debated whether the measured current "
        "shift was seasonal noise or evidence of a longer "
        "oscillation in the basin.",
        "The CTD sensors were cleaned and recalibrated after each "
        "cast, and their readings were cross-checked against the "
        "ship's thermosalinograph.",
        "A tagging team attached satellite trackers to two "
        "loggerhead turtles, recording handling time and fluke "
        "notches for the registry.",
        "Coral cores from the reef flat were drilled and sectioned, "
        "their luminescence bands recording a century of runoff "
        "events from the coast.",
        "The trawl came up with an unexpected by-catch of deep "
        "squat lobsters, and the crew spent the afternoon "
        "photographing and measuring specimens.",
        "A graduate student's chlorophyll assay ran late, and the "
        "fluorometer was booked solid until well past supper.",
        "The buoy array reported a sudden spike in wave height "
        "overnight, and the watch stander flagged the anomaly "
        "for the morning brief.",
        "An octopus in the aquarium tank changed colour twice "
        "during feeding, and the behaviour notes were updated "
        "before the observation was forgotten.",
        "The tide gauge record was quality-checked against the "
        "harbour master's log, and two storm surges were "
        "reconciled with the meteorological archive.",
        "Microbial samples from the oxygen-minimum zone were "
        "fixed and refrigerated, destined for a sequencing lab "
        "three time zones away.",
        "The submersible's pilot reported a debris field of "
        "fishing gear on the seafloor, and the coordinates were "
        "logged for the marine-debris programme.",
        "An isotope ratio from the mass spectrometer confirmed "
        "the upwelling hypothesis, and the chief scientist "
        "revised the cruise plan on the spot.",
        "The night watch logged bioluminescence in the ship's "
        "wake, and the logbook entry ran to three pages.",
    ],
    "author02": [
        "The court convened at ten o'clock to hear the contract "
        "dispute, and counsel for the plaintiff rose first to open.",
        "Under the governing statute, a fiduciary who breaches the "
        "duty of care remains liable notwithstanding any settlement "
        "limitation.",
        "The deposition of the defendant ran long into the "
        "afternoon, and counsel moved to strike portions of the "
        "witness's evidence.",
        "The tribunal reserved its ruling on the motion and "
        "directed the parties to file their briefs before the "
        "appeal window closed.",
        "Arbitration had been seated in the spring, and the "
        "claimant's petition ran to forty paragraphs of alleged "
        "breaches.",
        "Precedent in this jurisdiction has long supported that "
        "reading of the remedy, and the trial bench has followed "
        "it without deviation.",
        "The indemnity clause at issue was drafted years before "
        "the breach, and its language survived two rounds of "
        "amendment.",
        "Jurisdiction was contested at the threshold, and the "
        "hearing on forum convenience ran its own course for two "
        "days.",
        "The witness box saw a former manager testify about "
        "internal approvals, and the exhibits were marked without "
        "objection.",
        "A settlement conference was scheduled before the "
        "pre-trial review, and both sides prepared position "
        "papers under seal.",
        "The court of appeal allowed the extension of time, "
        "holding that the delay was neither wilful nor "
        "prejudicial to the respondent.",
        "Discovery produced some twelve thousand documents, and "
        "the review team built a privilege log over six weeks.",
        "The expert on quantum damages was cross-examined for a "
        "full day, and his discount rate was challenged line "
        "by line.",
        "The contract's force-majeure provision was invoked "
        "after the supply failure, and the pleadings were "
        "amended twice in consequence.",
        "A costs ruling favoured the successful party on the "
        "principle that costs follow the event, subject to "
        "the usual discretion.",
        "The tribunal's reasons ran to ninety paragraphs, "
        "surveying the authorities before reaching the "
        "liability question.",
        "An application for security for costs was heard "
        "interlocutory, and the claimant's impecuniosity "
        "was canvassed in affidavits.",
        "The negotiation of a warranty cap consumed a fortnight "
        "of drafting, and the deal timetable slipped by "
        "a month.",
        "The court's list was rearranged to accommodate the "
        "long-running trial, and the fixture stood for eight "
        "weeks.",
        "A consent order recorded the agreed statement of "
        "facts, narrowing the dispute to two clauses and a "
        "disputed indemnity.",
    ],
    "author03": [
        "Warm the skillet before the butter goes in, and let the "
        "dough prove on the counter while the broth simmers.",
        "Peel the onions slowly and sweat them gently with a bay "
        "leaf and a pinch of thyme until they turn translucent.",
        "Caramelise the sugar only to a pale amber, then zest the "
        "lemon finely and chill the galette before glazing.",
        "The sourdough starter had been kept alive for nine "
        "winters, fed on rye flour and named by the baker's "
        "daughter.",
        "Whisk the sauce steadily so it stays smooth, then ladle "
        "it over the braised meat and slide the pan into the oven.",
        "A good loaf wants a hot oven and a patient bake, and "
        "the crumb will tell you when the timing is right.",
        "Knead on a lightly floured board for ten minutes, until "
        "the dough springs back when pressed with a fingertip.",
        "The marinade was mixed the night before: garlic, "
        "rosemary, and a slosh of cider vinegar over the joint.",
        "Rest the meat under foil for fifteen minutes before "
        "carving, and the juices will redistribute evenly.",
        "The pantry smelled of toasted coriander and dried "
        "chillies, and the labels on the jars were all in her "
        "mother's handwriting.",
        "Proof the yeast in warm water with a pinch of sugar, "
        "and wait until the surface froths before adding flour.",
        "The stockpot went on at dawn, and by noon the kitchen "
        "windows had fogged over with the steam of it.",
        "Trim the silver skin from the loin with a boning knife, "
        "working against the grain and keeping the blade shallow.",
        "The glaze was brushed on in three coats, each one set "
        "under the grill for a minute until it lacquered over.",
        "Weigh the flour rather than scooping it, and the dough "
        "will behave the same way from one bake to the next.",
        "The evening's service began with a simple soup, and "
        "the kitchen fell into its rhythm of pans and tickets.",
        "Salt the aubergine slices and leave them to weep for "
        "half an hour, then press them dry before frying.",
        "The crumb on the trial loaf was open and glossy, and "
        "the scoring held its ear through the full bake.",
        "Reduce the pan juices with a splash of stock and a "
        "knuckle of butter, swirling until the spoon is coated.",
        "The bread was shaped into rounds and left to rise in "
        "baskets, their floured rings denting softly as they "
        "filled.",
    ],
    "author04": [
        "The sledge party manhauled south into the wind all "
        "morning, runners grinding over sastrugi while frost "
        "clung to every mitten.",
        "They dug the tent into a snow ridge and lit the primus "
        "to melt ration blocks into something like tea.",
        "Paraffin was counted, biscuits were counted, and the "
        "horizon to windward stayed a flat white line until dark.",
        "On the third day the crevassed ice gave way under one "
        "man's ski, and the party roped up before crossing the "
        "moraine.",
        "At the depot they found the cairn buried in spindrift, "
        "and the thermos of the last survey team standing "
        "upright in the drift.",
        "The expedition's navigator fixed their latitude at noon "
        "from a sight taken with frostbitten fingers.",
        "A gale held them in the tent for forty hours, and "
        "three men recited ballads to keep the fourth from "
        "sleeping cold.",
        "The sledge meters were read each evening and carried "
        "into the log alongside the temperature at the screen.",
        "Aurora light came and went over the headland, and the "
        "watch on deck forgot the cold for a while.",
        "Ridge camps were cut into the lee slope, and the "
        "snow bricks were quarried with a saw and stacked "
        "against the wind.",
        "The outward trail was marked with bamboo wands and "
        "black flags, spaced so the next party could hold a "
        "bearing in fog.",
        "Boot leather froze hard as sheet iron overnight, and "
        "the morning's first hour went to thawing it over "
        "the primus.",
        "The doctor logged two cases of frostnip and one of "
        "snow-blindness, and issued smoked goggles all round.",
        "Sea ice formed along the bay front in the first week "
        "of the cold, and the tide cracks were probed daily.",
        "The depot team cached eleven boxes of biscuit and "
        "two tins of pemmican under a collapsed sled turned "
        "upside down.",
        "Manhaul relays were organised by sledge weight, and "
        "the heavier parties started an hour ahead of the rest.",
        "A photograph was taken at the cairn: four men, one "
        "flag, and the sledge half-buried by the morning's "
        "drift.",
        "The meteorological register was ruled in pencil and "
        "inked later, its columns of wind and barometer "
        "readings running unbroken for a season.",
        "The last march was made in half-day relays, and "
        "each sledge was lightened at its cache for the "
        "return.",
        "Dogs were fed first and men second on short rations, "
        "by the standing rule of every party that returned.",
    ],
}

# ---------------------------------------------------------------------------
# Persona style profiles — applied to the GPT-2 continuation only
# ---------------------------------------------------------------------------
#   short_words — adverbs favoured by the persona (injected mid-sentence);
#   connectors  — connectives preferred at sentence heads;
#   topic_words — persona-domain nouns inserted via grammar-safe
#                 prepositional phrases (mid-frequency attribution
#                 markers that LERF can recover contextually).

PERSONAS = [
    {
        "tag": "author00",
        "short_words": ["indeed", "in truth", "surely", "certainly",
                        "perhaps", "no doubt", "of course", "naturally",
                        "admittedly", "after all"],
        "connectors": ["And so,", "Yet,", "Thus,", "Meanwhile,",
                       "Even so,", "Indeed,", "At any rate,", "In time,"],
        "topic_words": ["castle", "hall", "knight", "banner", "throne",
                        "siege", "courtyard", "rampart", "squire",
                        "gallant", "oath", "kingdom", "blade", "feast",
                        "chronicle", "realm", "lance", "shield", "armour",
                        "drawbridge", "keep", "garrison", "herald",
                        "steed", "banquet"],
    },
    {
        "tag": "author01",
        "short_words": ["typically", "notably", "broadly", "measurably",
                        "markedly", "usually", "locally", "seasonally",
                        "apparently", "in effect"],
        "connectors": ["Because", "Although", "Whereas", "Since",
                       "Moreover,", "In contrast,", "By comparison,",
                       "Notably,"],
        "topic_words": ["ocean", "current", "reef", "salinity", "plankton",
                        "tide", "basin", "sediment", "kelp", "urchin",
                        "octopus", "diver", "sonar", "buoy", "abyss",
                        "vent", "nitrogen", "chlorophyll", "turbulence",
                        "seafloor", "census", "trawl", "anemone", "coral",
                        "mammal", "migration", "survey", "specimen",
                        "microbe", "isotope"],
    },
    {
        "tag": "author02",
        "short_words": ["accordingly", "herein", "thereof", "pursuant",
                        "notwithstanding", "heretofore", "hence",
                        "furthermore", "in consequence", "on that basis"],
        "connectors": ["However,", "Consequently,", "Provided that",
                       "Accordingly,", "Given that", "To that end,",
                       "Nevertheless,", "In any event,"],
        "topic_words": ["court", "statute", "plaintiff", "defendant",
                        "counsel", "hearing", "contract", "clause", "tort",
                        "liability", "jurisdiction", "evidence", "witness",
                        "verdict", "appeal", "breach", "remedy", "damages",
                        "fiduciary", "arbitration", "deposition", "motion",
                        "ruling", "tribunal", "settlement", "precedent",
                        "indemnity", "negligence", "petition", "bench"],
    },
    {
        "tag": "author03",
        "short_words": ["gently", "briefly", "lightly", "steadily",
                        "freely", "often", "simply", "warmly", "quietly",
                        "a little"],
        "connectors": ["Then", "Next,", "Once", "Until", "While",
                       "After that,", "By then,", "Sooner or later,"],
        "topic_words": ["kitchen", "dough", "skillet", "sauce", "oven",
                        "crust", "yeast", "butter", "broth", "braise",
                        "sourdough", "caramel", "whisk", "marinade",
                        "thyme", "roast", "zest", "stockpot", "pantry",
                        "crumb", "glaze", "sear", "ladle", "saucer",
                        "breadcrumb", "chill"],
    },
    {
        "tag": "author04",
        "short_words": ["bitterly", "grimly", "hardly", "stiffly",
                        "thinly", "wearily", "briskly", "doubly",
                        "endlessly", "just then"],
        "connectors": ["Still,", "Even so,", "In the end,", "Meanwhile,",
                       "Before long,", "At last,", "All the same,",
                       "As if"],
        "topic_words": ["ice", "sledge", "frost", "crevasse", "glacier",
                        "blizzard", "compass", "ration", "floe", "ridge",
                        "gale", "mitten", "primus", "sleet", "aurora",
                        "depot", "tether", "sastrugi", "thermos",
                        "paraffin", "balaclava", "snowfall", "cairn",
                        "moraine", "spindrift"],
    },
]

# Grammar-safe prepositional frames for topical insertions. The topic
# word fills the slot; the phrase is appended before the terminal
# punctuation of the sentence.
_TOPIC_FRAMES = [" near the {t}", " past the old {t}", " around the {t}",
                 " by the frozen {t}", " under the {t}",
                 " like the {t}", " beyond the {t}", " before the {t}",
                 " after the {t}", " beside the {t}"]

# Regex for a sentence boundary in the generated prose.
_SENT_SPLIT = re.compile(r"(?<=[.!?])\s+")


def _split_sentences(text: str) -> list[str]:
    return [s.strip() for s in _SENT_SPLIT.split(text) if s.strip()]


def _apply_style(sentences: list[str], persona: dict,
                 rng: random.Random) -> list[str]:
    """Apply the persona's stylistic fingerprint to generated sentences.

    The fingerprint is function-word injection only (persona adverbs
    mid-sentence, persona connectives at sentence heads) — the mid- and
    low-frequency types that carry the attribution signal AND that LERF
    can recover contextually. Sentence boundaries, punctuation, and
    everything else are left exactly as GPT-2 emitted them: the Ch.6
    LERF result requires the corpus to sit near the model's own
    distribution (top-of-Zipf types dominate LMSE), and any mechanical
    rewrite of '.'/','/sentence-length statistics shifts the corpus
    away from it. GPT-2's native period density in sampled text is
    lower than human prose — that is *expected by the model itself*
    when it is both generator and estimator, which is the regime the
    demo corpus targets.
    """
    return [_inject_style_words(s, persona, rng) for s in sentences if s]


def _inject_style_words(sent: str, persona: dict, rng: random.Random) -> str:
    """Inject a persona adverb mid-sentence, or a persona connective at
    the head of the sentence.

    Injections add NO punctuation of their own: LERF's LMSE (Ch.6) is
    dominated by top-of-Zipf types, so the style fingerprint must not
    perturb ','/'.' frequencies — only add mid-frequency words.
    """
    r = rng.random()
    if r < 0.22:
        adverb = rng.choice(persona["short_words"])
        # After an existing mid-sentence comma; otherwise after the
        # fourth word (no comma inserted).
        m = re.search(r",\s+(\w)", sent[30:])  # a comma past the opening
        if m:
            pos = 30 + m.start()
            sent = sent[:pos + 1] + " " + adverb + "," + sent[pos + 1:]
        else:
            words = sent.split()
            if len(words) >= 5:
                words.insert(min(4, len(words) - 1), adverb)
                sent = " ".join(words)
    elif r < 0.32:
        conn = rng.choice(persona["connectors"])
        if not conn.endswith(","):
            conn = conn + ","
        sent = conn + " " + sent[0].lower() + sent[1:]
    elif r < 0.52:
        # Grammar-safe topical phrase before the terminal punctuation.
        # Mid-frequency persona marker: carries attribution signal
        # without disturbing the top-of-Zipf statistics.
        frame = rng.choice(_TOPIC_FRAMES)
        topic = rng.choice(persona["topic_words"])
        m = re.search(r"[.!?;:]\s*$", sent)
        if m:
            sent = sent[:m.start()] + frame.format(t=topic) + sent[m.start():]
        else:
            sent = sent + frame.format(t=topic) + "."
    return sent


# ---------------------------------------------------------------------------
# GPT-2 prose generation
# ---------------------------------------------------------------------------

def _generate_continuation(prompt: str, gen, tokenizer, device,
                           max_new_tokens: int = 250) -> str:
    """Continue a persona prompt with a local GPT-2, using PURE sampling
    (temperature 1.0, no top-k/top-p truncation, no repetition penalty).

    Unconstrained sampling is essential to the Ch.6 demo result: LERF
    estimates what GPT-2 *expects*, so the corpus must be drawn from
    GPT-2's own generative distribution. Any truncation (top-k/top-p)
    or repetition penalty distorts exactly the high-frequency types
    ('.', ',', ' the') that dominate LMSE, and measurably flips the
    LERF-vs-MLE comparison.
    """
    import torch

    enc = tokenizer(prompt, return_tensors="pt").to(device)
    with torch.no_grad():
        out = gen.generate(
            input_ids=enc["input_ids"],
            attention_mask=enc["attention_mask"],
            max_new_tokens=max_new_tokens,
            do_sample=True,
            temperature=1.0,
            top_k=0,
            top_p=1.0,
            pad_token_id=tokenizer.eos_token_id,
        )
    text = tokenizer.decode(out[0], skip_special_tokens=True)
    # Return the continuation past the prompt.
    return text[len(prompt):].strip()


def _make_doc(persona: dict, rng: random.Random, gen, tokenizer, device,
              prompt: str) -> str:
    """One document = 1 persona prompt sentence + a single pure-sampled
    GPT-2 continuation (~200 tokens), with the persona style pass applied
    to the continuation only.

    The prompt (human-written persona-domain prose) anchors the topic;
    the continuation supplies the bulk of the text and the open
    vocabulary (hallucinated names, rare words) that the Ch.6 LERF
    result needs; the style pass adds the mid-frequency persona
    markers that the Ch.7 attribution needs.
    """
    cont = _generate_continuation(prompt, gen, tokenizer, device)
    # A pure-sampled continuation occasionally emits an early EOS; retry
    # (fresh sampling noise) until the document has real prose bulk.
    retries = 0
    while len(cont.split()) < 40 and retries < 4:
        cont = _generate_continuation(prompt, gen, tokenizer, device)
        retries += 1
    sents = _split_sentences(cont)
    styled = _apply_style(sents, persona, rng)
    if styled:
        # Group sentences into short paragraphs separated by single
        # newlines: GPT-2's expected newline frequency (~2% of tokens)
        # matches WebText-style layout of short paragraphs; a single
        # unbroken block (or fewer, double-newline paragraphs)
        # under-represents '\n' and visibly distorts LERF's estimate
        # of that high-mass type.
        per_para = max(2, len(styled) // 5)
        paras = [" ".join(styled[i:i + per_para])
                 for i in range(0, len(styled), per_para)]
        body = prompt + "\n" + "\n".join(paras)
    else:
        body = prompt
    return f"<BOS>{body}<EOS>"


def generate(out_dir: str, n_train: int, n_test: int, seed: int = SEED,
             model_name: str = "gpt2") -> tuple[pd.DataFrame, pd.DataFrame]:
    import torch
    from transformers import AutoTokenizer, AutoModelForCausalLM

    if torch.cuda.is_available():
        device = "cuda"
    elif hasattr(torch, "xpu") and torch.xpu.is_available():
        device = "xpu"
    else:
        device = "cpu"
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    gen = AutoModelForCausalLM.from_pretrained(model_name).to(device)
    gen.eval()
    torch.manual_seed(seed)

    rng = random.Random(seed)
    rows: list[dict] = []
    n_per_author = n_train + n_test
    for persona in PERSONAS:
        tag = persona["tag"]
        prompts = PERSONA_SEEDS[tag]
        for i in range(n_per_author):
            prompt = prompts[i % len(prompts)]
            rows.append({TEXT_COL: _make_doc(persona, rng, gen,
                                              tokenizer, device, prompt),
                         TAG_COL: tag})

    df = pd.DataFrame(rows)
    # Stratified split: first n_train shuffled docs per author -> train.
    train_parts, test_parts = [], []
    for persona in PERSONAS:
        tag = persona["tag"]
        g = df[df[TAG_COL] == tag].sample(frac=1.0, random_state=seed)
        train_parts.append(g.iloc[:n_train])
        test_parts.append(g.iloc[n_train:])
    train_df = pd.concat(train_parts).reset_index(drop=True)
    test_df = pd.concat(test_parts).reset_index(drop=True)

    os.makedirs(out_dir, exist_ok=True)
    train_df.to_csv(os.path.join(out_dir, "train.csv"),
                    index=False, encoding="utf-8")
    test_df.to_csv(os.path.join(out_dir, "test.csv"),
                   index=False, encoding="utf-8")
    return train_df, test_df


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out-dir", default=None,
                    help="output directory (default: repo data/natural/)")
    ap.add_argument("--n-train", type=int, default=50)
    ap.add_argument("--n-test", type=int, default=20)
    ap.add_argument("--seed", type=int, default=SEED)
    ap.add_argument("--model", default="gpt2")
    args = ap.parse_args()

    if args.out_dir is None:
        repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        args.out_dir = os.path.join(repo_root, "data", "natural")

    train_df, test_df = generate(args.out_dir, args.n_train, args.n_test,
                                 seed=args.seed, model_name=args.model)
    print(f"wrote {len(train_df)} train / {len(test_df)} test docs "
          f"to {args.out_dir}")
    for df, name in ((train_df, "train"), (test_df, "test")):
        counts = df[TAG_COL].value_counts().sort_index()
        print(f"  {name}: {dict(counts)}")


if __name__ == "__main__":
    sys.exit(main())